services:

  unix.timeProvider:
    class: Lexide\Chronos\TimeProvider\TimeProvider

  milli.timeProvider:
    class: Lexide\Chronos\TimeProvider\MilliTimeProvider

  micro.timeProvider:
    class: Lexide\Chronos\TimeProvider\MicroTimeProvider

  nano.timeProvider:
    class: Lexide\Chronos\TimeProvider\NanoTimeProvider

  default.timeProvider:
    aliasOf: "@micro.timeProvider"

  stopWatch:
    class: Lexide\Chronos\StopWatch
    arguments:
      - "@default.timeProvider"